export const SITES = {
  ctc: {
    id: 'ctc',
    name: 'Cape Town Concierge',
    domain: 'capetown-concierge.co.za',
    baseUrl: 'https://www.capetown-concierge.co.za',
    color: '#16a05a',
    repo: 'mohamadxnadeem/capetown-concierge',
    branch: 'main',
    pages: [
      { id: 'home', name: 'Homepage', path: '/', filePath: 'app/page.tsx', cat: 'Main',
        primaryKw: 'luxury chauffeur Cape Town',
        secondary: ['private chauffeur Cape Town', 'chauffeur service Cape Town'] },
      { id: 'chauffeur', name: 'Chauffeur Services', path: '/chauffeur-services', filePath: 'app/chauffeur-services/page.tsx', cat: 'Main',
        primaryKw: 'private chauffeur hire Cape Town',
        secondary: ['hire a driver Cape Town', 'personal driver Cape Town'] },
      { id: 'tours', name: 'Private Tours', path: '/private-tours', filePath: 'app/private-tours/page.tsx', cat: 'Main',
        primaryKw: 'private tours Cape Town',
        secondary: ['luxury tours Cape Town', 'Cape Town private guided tour'] },
      { id: 'airport', name: 'Airport Transfers', path: '/airport-transfers-cape-town', filePath: 'app/airport-transfers-cape-town/page.tsx', cat: 'Main',
        primaryKw: 'airport transfer Cape Town',
        secondary: ['luxury airport transfer Cape Town', 'Cape Town airport pickup'] },
      { id: 'wine-farms', name: 'Wine Farms Guide', path: '/best-wine-farms-in-cape-town', filePath: 'app/best-wine-farms-in-cape-town/page.tsx', cat: 'Main',
        primaryKw: 'best wine farms Cape Town',
        secondary: ['Cape Town wine tasting tour', 'Stellenbosch wine estates'] },
      { id: 'activities', name: 'Experiences', path: '/best-activities-to-do-in-cape-town', filePath: 'app/best-activities-to-do-in-cape-town/page.tsx', cat: 'Main',
        primaryKw: 'best things to do in Cape Town',
        secondary: ['Cape Town experiences', 'activities Cape Town tourists'] },
      { id: 'itinerary', name: '7-Day Itinerary', path: '/7-day-cape-town-itinerary', filePath: 'app/7-day-cape-town-itinerary/page.tsx', cat: 'Main',
        primaryKw: '7 day Cape Town itinerary',
        secondary: ['Cape Town travel itinerary', 'one week Cape Town'] },
      { id: 'peninsula', name: 'Cape Peninsula Tour', path: '/private-tours/cape-peninsula-tour', filePath: 'app/private-tours/cape-peninsula-tour/page.tsx', cat: 'Tours',
        primaryKw: 'Cape Peninsula private tour',
        secondary: ['Cape Point tour Cape Town', 'Boulders Beach penguin tour'] },
      { id: 'winelands', name: 'Winelands Tour', path: '/private-tours/winelands-chauffeur-drive', filePath: 'app/private-tours/winelands-chauffeur-drive/page.tsx', cat: 'Tours',
        primaryKw: 'Stellenbosch Winelands private tour',
        secondary: ['Franschhoek wine tour private', 'winelands chauffeur Cape Town'] },
      { id: 'city-tour', name: 'City & Table Mountain', path: '/private-tours/cape-town-city-tour', filePath: 'app/private-tours/cape-town-city-tour/page.tsx', cat: 'Tours',
        primaryKw: 'Cape Town city tour private chauffeur',
        secondary: ['Table Mountain private tour', 'Bo-Kaap guided tour'] },
      { id: 'safari', name: 'Sunset Safari', path: '/private-tours/sunset-safari-experience', filePath: 'app/private-tours/sunset-safari-experience/page.tsx', cat: 'Tours',
        primaryKw: 'Aquila safari day trip Cape Town',
        secondary: ['Big 5 safari Cape Town', 'safari day trip from Cape Town'] },
      { id: 'bmw5', name: 'BMW 5-Series', path: '/chauffeur-services/bmw-5-series-for-hire-with-driver', filePath: 'app/chauffeur-services/bmw-5-series-for-hire-with-driver/page.tsx', cat: 'Vehicles',
        primaryKw: 'BMW 5 Series chauffeur Cape Town', secondary: ['executive sedan hire Cape Town'] },
      { id: 'bmwx5', name: 'BMW X5', path: '/chauffeur-services/BMW-X5-for-hire-with-driver', filePath: 'app/chauffeur-services/BMW-X5-for-hire-with-driver/page.tsx', cat: 'Vehicles',
        primaryKw: 'BMW X5 chauffeur Cape Town', secondary: ['luxury SUV hire Cape Town'] },
      { id: 'staria', name: 'Hyundai Staria', path: '/chauffeur-services/8-seater-staria-van-with-driver', filePath: 'app/chauffeur-services/8-seater-staria-van-with-driver/page.tsx', cat: 'Vehicles',
        primaryKw: '8 seater van hire Cape Town', secondary: ['group transfer Cape Town'] },
      { id: 'sclass', name: 'Mercedes S-Class', path: '/chauffeur-services/Mercedes-s-class-for-hire-with-driver', filePath: 'app/chauffeur-services/Mercedes-s-class-for-hire-with-driver/page.tsx', cat: 'Vehicles',
        primaryKw: 'Mercedes S-Class hire Cape Town', secondary: ['VIP chauffeur Cape Town'] },
      { id: 'sprinter', name: 'Mercedes Sprinter', path: '/chauffeur-services/Mercedes-sprinter-with-driver-cape-town', filePath: 'app/chauffeur-services/Mercedes-sprinter-with-driver-cape-town/page.tsx', cat: 'Vehicles',
        primaryKw: 'Mercedes Sprinter hire Cape Town', secondary: ['14 seater van Cape Town'] },
      { id: 'vclass', name: 'Mercedes V-Class', path: '/chauffeur-services/Mercedes-v-class-private-chauffeur-service', filePath: 'app/chauffeur-services/Mercedes-v-class-private-chauffeur-service/page.tsx', cat: 'Vehicles',
        primaryKw: 'Mercedes V-Class chauffeur Cape Town', secondary: ['luxury group transport Cape Town'] },
      { id: 'rangerover', name: 'Range Rover Sport', path: '/chauffeur-services/range-rover-sport-chauffeur-service', filePath: 'app/chauffeur-services/range-rover-sport-chauffeur-service/page.tsx', cat: 'Vehicles',
        primaryKw: 'Range Rover chauffeur Cape Town', secondary: ['Range Rover hire Cape Town'] },
    ]
  },

  sigma: {
    id: 'sigma',
    name: 'Sigma VIP',
    domain: 'sigmachauffeur.vip',
    baseUrl: 'https://sigmachauffeur.vip',
    color: '#c9982a',
    repo: 'mohamadxnadeem/sigma-chauffeur',
    branch: 'main',
    pages: [
      { id: 'home', name: 'Homepage', path: '/', filePath: 'app/page.tsx', cat: 'Main',
        primaryKw: 'VIP chauffeur service Cape Town',
        secondary: ['premium chauffeur Cape Town', 'luxury transport Cape Town'] },
      { id: 'chauffeur', name: 'Chauffeur Services', path: '/chauffeur-services', filePath: 'app/chauffeur-services/page.tsx', cat: 'Main',
        primaryKw: 'chauffeur service Cape Town',
        secondary: ['professional driver Cape Town', 'private driver hire Cape Town'] },
      { id: 'airport', name: 'Airport Transfers', path: '/airport-transfers-cape-town', filePath: 'app/airport-transfers-cape-town/page.tsx', cat: 'Main',
        primaryKw: 'luxury airport transfer Cape Town',
        secondary: ['Cape Town airport chauffeur', 'CPT airport private transfer'] },
      { id: 'wine-farms', name: 'Wine Farms Guide', path: '/best-wine-farms-in-cape-town', filePath: 'app/best-wine-farms-in-cape-town/page.tsx', cat: 'Main',
        primaryKw: 'Cape Town wine tour private driver',
        secondary: ['Stellenbosch wine tasting tour', 'Franschhoek wine farms'] },
      { id: 'activities', name: 'Cape Town Activities', path: '/best-activities-to-do-in-cape-town', filePath: 'app/best-activities-to-do-in-cape-town/page.tsx', cat: 'Main',
        primaryKw: 'Cape Town activities private tour',
        secondary: ['things to do Cape Town with driver', 'Cape Town sightseeing'] },
      { id: 'itinerary', name: '7-Day Itinerary', path: '/7-day-cape-town-itinerary', filePath: 'app/7-day-cape-town-itinerary/page.tsx', cat: 'Main',
        primaryKw: 'Cape Town 7 day travel guide',
        secondary: ['Cape Town itinerary planning', 'week in Cape Town luxury'] },
      { id: 'contact', name: 'Contact', path: '/contact', filePath: 'app/contact/page.tsx', cat: 'Main',
        primaryKw: 'book VIP chauffeur Cape Town',
        secondary: ['hire chauffeur Cape Town', 'Cape Town chauffeur booking'] },
      { id: 'peninsula', name: 'Cape Peninsula Tour', path: '/private-tours/cape-peninsula-tour', filePath: 'app/private-tours/cape-peninsula-tour/page.tsx', cat: 'Tours',
        primaryKw: 'Cape Peninsula tour with driver Cape Town',
        secondary: ['Cape Point private day tour', 'Boulders Beach private transfer'] },
      { id: 'winelands', name: 'Winelands Tour', path: '/private-tours/winelands-chauffeur-drive', filePath: 'app/private-tours/winelands-chauffeur-drive/page.tsx', cat: 'Tours',
        primaryKw: 'Winelands private chauffeur Cape Town',
        secondary: ['Stellenbosch wine day trip', 'Cape Winelands private tour'] },
      { id: 'city-tour', name: 'City & Table Mountain', path: '/private-tours/cape-town-city-tour', filePath: 'app/private-tours/cape-town-city-tour/page.tsx', cat: 'Tours',
        primaryKw: 'Cape Town sightseeing private driver',
        secondary: ['Table Mountain tour private', 'Cape Town city highlights tour'] },
      { id: 'safari', name: 'Sunset Safari', path: '/private-tours/sunset-safari-experience', filePath: 'app/private-tours/sunset-safari-experience/page.tsx', cat: 'Tours',
        primaryKw: 'safari day trip Cape Town private',
        secondary: ['Aquila game reserve Cape Town', 'Big 5 day tour Cape Town'] },
      { id: 'bmw5', name: 'BMW 5-Series', path: '/chauffeur-services/bmw-5-series-for-hire-with-driver', filePath: 'app/chauffeur-services/bmw-5-series-for-hire-with-driver/page.tsx', cat: 'Vehicles',
        primaryKw: 'BMW 5 Series private driver Cape Town', secondary: ['executive car Cape Town'] },
      { id: 'bmwx5', name: 'BMW X5', path: '/chauffeur-services/bmw-x5-for-hire-with-driver', filePath: 'app/chauffeur-services/bmw-x5-for-hire-with-driver/page.tsx', cat: 'Vehicles',
        primaryKw: 'BMW X5 private hire Cape Town', secondary: ['luxury SUV driver Cape Town'] },
      { id: 'staria', name: 'Hyundai Staria', path: '/chauffeur-services/8-seater-staria-van-with-driver', filePath: 'app/chauffeur-services/8-seater-staria-van-with-driver/page.tsx', cat: 'Vehicles',
        primaryKw: '8 seater minibus hire Cape Town', secondary: ['group tour Cape Town'] },
      { id: 'sclass', name: 'Mercedes S-Class', path: '/chauffeur-services/mercedes-s-class-for-hire-with-driver', filePath: 'app/chauffeur-services/mercedes-s-class-for-hire-with-driver/page.tsx', cat: 'Vehicles',
        primaryKw: 'Mercedes S-Class VIP Cape Town', secondary: ['luxury sedan Cape Town'] },
      { id: 'sprinter', name: 'Mercedes Sprinter', path: '/chauffeur-services/mercedes-sprinter-with-driver-cape-town', filePath: 'app/chauffeur-services/mercedes-sprinter-with-driver-cape-town/page.tsx', cat: 'Vehicles',
        primaryKw: 'Mercedes Sprinter group hire Cape Town', secondary: ['large group transport Cape Town'] },
      { id: 'vclass', name: 'Mercedes V-Class', path: '/chauffeur-services/mercedes-v-class-private-chauffeur-service', filePath: 'app/chauffeur-services/mercedes-v-class-private-chauffeur-service/page.tsx', cat: 'Vehicles',
        primaryKw: 'Mercedes V-Class private hire Cape Town', secondary: ['minivan chauffeur Cape Town'] },
      { id: 'rangerover', name: 'Range Rover Sport', path: '/chauffeur-services/range-rover-sport-chauffeur-service', filePath: 'app/chauffeur-services/range-rover-sport-chauffeur-service/page.tsx', cat: 'Vehicles',
        primaryKw: 'Range Rover Sport hire Cape Town', secondary: ['luxury 4x4 Cape Town'] },
    ]
  }
}

export const SITE_LIST = [SITES.ctc, SITES.sigma]
